accounts/urls.py
from django.urls import path, include
from accounts.views import login_view, signup_view, logout_view

app_name = 'accounts'

urlpatterns = [
	path('register/', signup_view, name='signup'),
	path('login/', login_view, name='login'),
	path('logout/', logout_view, name='logout'),
]

api/urls.py
from django.urls import path
from .views import ( find_match, create_review, 
					 email_subscription )

app_name = 'api'

urlpatterns = [
    # Other URLs you want to include
    path('match/', find_match, name='find_match'),
    path('review/create/', create_review, name='create_review'),
    path('subscription/create/', email_subscription, name='email_subscription'),
]

corider/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
    path('', include('rides.urls', namespace='rides')),
    path('api/v1/', include('api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='account')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rides/urls.py
from django.urls import path

from .views import ( home, about, contact, 
		             team, services, ride,
		     		 match, ride_detail,
		     		 end_trip, request, decline, 
		     		 account, profile, 
		     		 edit_account, rides,
		     		 reviews, terms, privacy,
		     		 profile_reviews, error_404_page )

app_name = 'rides'

urlpatterns = [
    # Other URLs you want to include
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('team/', team, name='team'),
    path('services/', services, name='services'),
    path('ride/', ride, name='ride'),
    path('rides/', rides, name='rides'),
    path('ride-detail/<int:ride_id>', ride_detail, name='ride_detail'),
    path('request/', request, name='request'),
    path("end-ride/", end_trip, name="end_ride"),
    path("match/", match, name="match"),
    path("decline/", decline, name="decline"),
    path("account/", account, name="account"),
    path("account/edit", edit_account, name="edit_account"),
    path("profile/<str:username>", profile, name="profile"),
    path("reviews/", reviews, name="reviews"),
    path("reviews/<str:username>", profile_reviews, name="profile_reviews"),
    path("terms/", terms, name="terms"),
    path("privacy/", privacy, name="privacy"),
    path("404/", error_404_page, name="404"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
	MALE = 'male'
	FEMALE = 'female'

	GENDER_CHOICES = [
		(MALE, 'male'),
		(FEMALE, 'female')
	]
	
	username = models.CharField(max_length=255, unique=True)
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	gender = models.CharField(max_length=255, choices=GENDER_CHOICES,  null=True, blank=True)
	profile_picture = models.ImageField(upload_to='uploads/profile-pictures/')
	birthday = models.DateField( null=True, blank=True )
	email = models.EmailField(max_length=255, null=True, blank=True)
	phone_number = models.CharField(max_length=255,  null=True, blank=True)
	address = models.CharField(max_length=500,  null=True, blank=True)
	zip_code = models.CharField(max_length=255,  null=True, blank=True)
	total_rides = models.IntegerField(default=0)
	as_passenger = models.IntegerField(default=0)
	as_driver = models.IntegerField(default=0)
	verified = models.BooleanField(default=False)
	rating = models.DecimalField(default=0.0, decimal_places=1, max_digits=2)
	driver_id = models.CharField(max_length=255, null=True, blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class SignUpForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'autofocus': True}), 
							   required=True)
	

	class Meta:
		model = User
		fields = ('username', 'password1', 'password2')


class LoginForm(AuthenticationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'autofocus': True}), 
							   required=True)
	
	class Meta:
		model = User
		fields = ('username', 'password')


class EditAccountForm(forms.ModelForm):
	first_name = forms.CharField(required=True)
	last_name = forms.CharField(required=True)
	gender = forms.ChoiceField(required=True, choices=User.GENDER_CHOICES)
	phone_number = forms.CharField(required=True)
	address = forms.CharField(required=True)
	class Meta:
		model = User
		fields = ('first_name', 'last_name',
				  'gender', 'birthday',
				  'email' , 'phone_number', 
				  'address', 'zip_code',
				  'driver_id', 'profile_picture', )
		widgets = {
			'birthday': forms.DateInput(attrs={'type': 'date'})
		}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import ( logout, authenticate,
								 login, get_user_model )
from accounts.forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
import uuid

# Create your views here.

User = get_user_model()


def signup_view(request):
	if request.method == 'GET':
		form = SignUpForm()
	else:
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect('rides:home')
	context = {
		'title': 'Sign Up',
		'cache_id': uuid.uuid4(),
		'form': form
	}
	return render(request, 'accounts/signup.html', context)

	
def login_view(request):
	if request.user.is_authenticated:
		return redirect('rides:home')
	if request.method == 'GET':
		form = AuthenticationForm()
	else:
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get("username")
			password = form.cleaned_data.get("password")
			user = authenticate(request, username=username, password=password)
			if user is not None:
				next = request.GET.get('next', '/')
				login(request, user)
				return redirect(next)
			else:
				form.add_error(None, "Invalid username or password")
	context = {
		'title': 'Login',
		'cache_id': uuid.uuid4(),
		'form': form
	}
	return render(request, 'accounts/login.html', context)
	
def logout_view(request):
	if request.user:
		logout(request)
		return redirect('rides:home')
	return redirect('rides:home')

rides/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth import get_user_model
from django.db.models import Q, Avg
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from api.utils import match_routes
from rides.models import ( Ride, Review, Vehicle, 
						   Rating, Request, ContactMessage )
from accounts.forms import EditAccountForm
from rides.forms import VehicleForm, ContactMessageForm
import uuid
import ast
import json


User = get_user_model()

def home(request):
    context = {
    	'title': 'Home'
    }
    return render(request, 'rides/home.html', context)

def about(request):
    context = {
    	'title': 'About'
    }
    return render(request, 'rides/about.html', context)

def contact(request):
	context = {
    	'title': 'Contact',
    	'form': ContactMessageForm()
    }
	if request.method == 'POST':
		contact_message_form = ContactMessageForm(request.POST)
		if contact_message_form.is_valid():
			contact_message_form.save()
			return redirect('rides:home')
	return render(request, 'rides/contact.html', context)

def team(request):
    context = {
    	'title': 'Team'
    }
    return render(request, 'rides/team.html', context)

def services(request):
    context = {
    	'title': 'Services'
    }
    return render(request, 'rides/services.html', context)
    
def terms(request):
    context = {
    	'title': 'Terms'
    }
    return render(request, 'rides/terms.html', context)

def privacy(request):
    context = {
    	'title': 'Privacy'
    }
    return render(request, 'rides/privacy.html', context)

@login_required   
def ride(request):
    context = {
    	'title': 'Ride'
    }
    return render(request, 'rides/ride.html',  context)

@login_required   
def rides(request):
	rides = Ride.objects.filter(user=request.user).all()
	context = {
		'title': 'Rides',
		'rides': rides[::-1]
	}
	return render(request, 'rides/rides.html',  context)
	
@login_required   
def reviews(request):
	reviews = Review.objects.filter(user=request.user).all()
	context = {
		'title': 'Reviews',
		'reviews': reviews
	}
	return render(request, 'rides/reviews.html',  context)
	
@login_required   
def profile_reviews(request, username):
	user = User.objects.filter(username=username).first()
	if not user:
		return redirect('rides:404')
	reviews = Review.objects.filter(user=user).all()
	context = {
		'title': 'Profile Reviews',
		'reviews': reviews
	}
	return render(request, 'rides/reviews.html',  context)

@login_required    
def account(request):
	user = request.user
	vehicle = Vehicle.objects.filter(user=user).first()
	user_ratings = Rating.objects.filter(user=user)
	total_requests = Request.objects.filter(receiver=user).all()
	accepted_requests = Request.objects.filter(receiver=user, 
										status=Request.ACCEPTED).all()
	if len(total_requests) > 0:
		availability = ( len(accepted_requests) * 100 ) / len(total_requests)
		user.availability = int(availability)
	context = {
		'title': 'Account Information',
		'user': user,
		'vehicle': vehicle
	}
	return render(request, 'rides/account.html', context)
    
@login_required    
def edit_account(request):
	account = request.user
	vehicle = Vehicle.objects.filter(user=request.user).first()
	if request.method == "POST":
		account_form = EditAccountForm(request.POST, request.FILES, instance=account)
		if vehicle:
			vehicle_form = VehicleForm(request.POST, instance=vehicle)
		else:
			vehicle_form = VehicleForm(request.POST)
		if vehicle_form.is_empty():
			if account_form.is_valid():
				account = account_form.save(commit=False)
				account.verified = True
				account.save()
				if vehicle:
					vehicle.delete()
				return redirect('rides:account')
		else:
			if account_form.is_valid() and vehicle_form.is_valid():
				account = account_form.save(commit=False)
				vehicle = vehicle_form.save(commit=False)
				account.verified = True
				vehicle.user = request.user
				account.save()
				vehicle.save()
				return redirect('rides:account')
	else:
		account_form = EditAccountForm(instance=account)
		if vehicle:
			vehicle_form = VehicleForm(instance=vehicle)
		else:
			vehicle_form = VehicleForm()
	context = {
		'title': 'Edit Account',
		'account_form': account_form,
		'vehicle_form': vehicle_form
	}
	return render(request, 'rides/edit-account.html', context)

@login_required
def profile(request, username):
	user = User.objects.filter(username=username).first()
	if not user:
		return redirect('rides:404') 
	vehicle = Vehicle.objects.filter(user=user).first()
	user_ratings = Rating.objects.filter(user=user)
	total_requests = Request.objects.filter(receiver=user).all()
	accepted_requests = Request.objects.filter(receiver=user,
										status=Request.ACCEPTED).all()
	if len(total_requests) > 0:
		availability = ( len(accepted_requests) * 100 ) / len(total_requests)
		user.availability = int(availability)
	context = {
		'title': 'Profile',
    	'user': user,
    	'vehicle': vehicle
    }
	return render(request, 'rides/profile.html', context)   

@login_required
def ride_detail(request, ride_id):
	ride = Ride.objects.filter(user=request.user, id=ride_id).first()
	if not ride:
		return redirect('rides:404')
	matches = []    # possible matches
	requests = Request.objects.filter(receiver=request.user, r_ride=ride, 
									  status=Request.PENDING).all()
	sent_requests_q = Request.objects.filter(sender=request.user, s_ride=ride,
										   status=Request.PENDING).all()
	request_rides = []
	sent_requests = []
	for r in requests:
		request_rides.append(r.s_ride)
	for r in sent_requests_q:
		sent_requests.append(r.r_ride)
	if ride.role == 'passenger':	
		if ride.status == Ride.ACTIVE or ride.status == Ride.PENDING:
			rides = Ride.objects.filter(role=Ride.DRIVER).\
				     exclude(Q(user=request.user)).\
				     exclude(Q(status=Ride.INACTIVE))
			for mride in rides:
				# Convert the route string to a list of coordinates.
				ride_route = ast.literal_eval(mride.route)
				match_rate = match_routes(ast.literal_eval(ride.route), ride_route)
				if ( match_rate >= 0.4 and mride.user != ride.driver 
				     and mride not in request_rides and mride not in sent_requests):
					mride.match_rate = match_rate * 100
					mride.username = mride.user.username
					mride.profile_picture = mride.user.profile_picture.url
					mride.rating = mride.user.rating
					matches.append(vars(mride))
	else:	
		if ride.status == Ride.ACTIVE or ride.status == Ride.PENDING:
			rides = Ride.objects.filter(role=Ride.PASSENGER, status=Ride.PENDING).\
						    exclude(Q(user=request.user))
			for mride in rides:
				# Convert the route string to a list of coordinates.
				ride_route = ast.literal_eval(mride.route)
				match_rate = match_routes(ast.literal_eval(ride.route), ride_route)
				if ( match_rate >= 0.4 and mride not in ride.passengers.all()
				     and mride not in request_rides and mride not in sent_requests ):
					mride.match_rate = match_rate * 100
					mride.username = mride.user.username
					mride.profile_picture = mride.user.profile_picture.url
					mride.rating = mride.user.rating
					matches.append(vars(mride))
	passengers = ride.passengers.all()
	driver = ride.driver
	ride.user_id = ride.user.id
	ride = vars(ride)
	ride['requests'] = request_rides
	ride['passengers'] = passengers
	ride['driver'] = driver
	ride['sent_request'] = sent_requests
	context = {
		'title': 'Ride Detail',
		'ride': ride,
		'matches': matches,
		'cache_id': uuid.uuid4(),
	}
	return render(request, 'rides/ride-detail.html', context)

@login_required
def match(request):
	ride_id = request.GET.get('ride_id', None)
	match_id = request.GET.get('match_id', None)
	role = request.GET.get('role', None)
	ride = Ride.objects.filter(id=ride_id).first()
	match = Ride.objects.filter(id=match_id).first()
	req = Request.objects.\
				  filter(sender=match.user, receiver=ride.user,s_ride=match).\
				  first()
	if ride and match:
		if role == 'passenger':
			ride.driver = match
			match.passengers.add(ride)
		else:
			ride.passengers.add(match)
			match.driver = ride
		req.status = Request.ACCEPTED
		if ride.status == Ride.PENDING:
			ride.status = Ride.ACTIVE
		if match.status == Ride.PENDING:
			match.status = Ride.ACTIVE
		ride.save()
		match.save()
		req.save()
		return redirect('rides:ride_detail', ride_id=ride_id)  
	else:
		return render(request, 'rides/404.html', context)
	
@login_required	
def decline(request):
	ride_id = request.GET.get('ride_id')
	match_id = request.GET.get('match_id')
	ride = Ride.objects.filter(id=ride_id).first()
	match = Ride.objects.filter(id=match_id).first()
	if ride and match:
		req = Request.objects.\
					  filter(sender=match.user,receiver=ride.user,r_ride=ride).\
					  first()
		if not req:
			return redirect('rides:404')
		req.status = Request.DECLINED
		req.save()
		return redirect('rides:ride_detail', ride_id=ride_id)
	else:
		return redirect('rides:404')

@login_required    
def request(request):
	ride_id = request.GET.get('ride_id', None)
	match_id = request.GET.get('match_id', None)
	ride = Ride.objects.filter(id=ride_id).first()
	match = Ride.objects.filter(id=match_id).first()

	if ride and match:
		Request.objects.create(sender=ride.user, receiver=match.user,
							   r_ride=match, s_ride=ride)
	else:
		return redirect('rides:404')
	return redirect('rides:ride_detail', ride_id=ride_id)

@login_required	
def end_trip(request):
	if request.method == 'POST':
		ride_id = request.POST.get('ride_id')
		driver_name = request.POST.get('driver')
		review = request.POST.get('review')
		rate = request.POST.get('rating', 0)
		ride = Ride.objects.filter(user=request.user, id=ride_id).first()
		user = User.objects.filter(username=driver_name).first()
		if rate:
				rating = Rating.objects.create(user=user, rate=rate,
											   rater=request.user, ride=ride)
				user_ratings = Rating.objects.filter(user=user)
				if user_ratings:

rides/templates/rides/about.html
{% extends 'rides/main.html' %}
{% load static %}
{% block head %}
	<link rel="stylesheet" href="{% static 'css/home.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/about.css' %}"/>
	<script src="{% static 'js/about.js' %}" defer ></script>
{% endblock %}
{% block content %}
	<section class="about-hero">
		<div>
			<h2>About<span class="dot">.</span></h2>
			<div>
				<a href="/"><span>Home</span></a>
				<i class="fas fa-chevron-right"></i>
				<span>About</span>
			</div>
		</div>
	</section>
	<section class="main-wrapper">
		<div class="main">
			<div>
				<h4>About CoRider</h4>
				<h1>Trusted Cab Service All Over The World <span class="dot">.</span></h1>
				<p>
					CoRider is dedicated to providing safe, reliable, and cost-effective transportation solutions for commuters, travelers, and anyone in need of a ride, with a global network of trusted drivers and a commitment to exceptional customer service.
				</p>
				<div class="ul-wrapper">
					<ul>
						<li><i class="fas fa-check"></i><span>Flexible & Cost-Effective</span></li>
						<li><i class="fas fa-check"></i><span>VIP & Annual Pass Services</span></li>
						<li><i class="fas fa-check"></i><span>Over 250,000 Clients</span></li>
						<li><i class="fas fa-check"></i><span>Satisfaction Guarantee</span></li>
					</ul>
					<ul>
						<li><i class="fas fa-check"></i><span>Company Contract</span></li>
						<li><i class="fas fa-check"></i><span>Convenient Location</span></li>
						<li><i class="fas fa-check"></i><span>Home Pickup</span></li>
						<li><i class="fas fa-check"></i><span>One Way Rental</span></li>
					</ul>
				</div>
				<div class="cta">
					<div><img src="{% static '/images/cta-photo.jpg' %}" alt=""/></div>
					<div class="about-cta">
						<h5>We Are Available 24 Hours</h5>
						<p>For Booking :<span class="dot" style="font-weight: bold;">(+234) 915 354 7755</span></p>
					</div>
				</div>
			</div>
			<div class="about-images">
				<img src="{% static '/images/about-right.jpg' %}" alt="">
				<img src="{% static '/images/about-right-2.jpg' %}" alt="">
			</div>
		</div>
		<div class="offer-cards-wrapper">
			<div class="card">
				<div class="card-upper">
					<div class="dollar-icon"><i class="fas fa-dollar-sign"></i></div>
					<div >
						<p style="color: white;" >Payment Integration</p>
						<p style="color: white;">Secure and hassle-free</p>
					</div>
				</div>
				<div class="card-icons-wrapper">
					<span><i class="fas fa-brands fa-cc-mastercard"></i></span>
					<span><i class="fas fa-brands fa-cc-visa"></i></span>
					<span><i class="fas fa-brands fa-cc-stripe"></i></span>
					<span><i class="fas fa-brands fa-cc-paypal"></i></span>
				</div>
			</div>
			<div class="card">
				<div class="card-upper">
					<div class="privacy-icon"><i class="fas fa-shield-alt"></i></div>
					<div>
						<p>Safety First</p>
						<p style="color: black;">Your safety is out top priority</p>
					</div>
				</div>
				<div class="card-icons-wrapper">
					<span class="card-inline"><i class="fas fa-credit-card"></i><span>Gurantee </span></span>
					<span class="card-inline"><i class="fas fa-car"></i><span>Quick ride </span></span>
				</div>
			</div>
			<div class="card">
				<div class="card-upper">
					<div class="tablet-icon"><i class="fas fa-tablet"></i></div>
					<div>
						<p>100% Digital</p>
						<p style="color: #6d6d6d;">Streamlined digital experience</p>
					</div>
				</div>
				<div class="card-icons-wrapper">
					<span class="card-inline"><i class="fas fa-brands fa-apple" style="color: #FDB813"> </i><span>Apple</span> </span>
					<span class="card-inline"><i class="fas  fa-brands fa-android" style="color: #FDB813"></i><span>Android</span> </span>
				</div>
			</div>
		</div>
	</section>
	<section class='show'>
		<h4>Let's Ride With Us</h4>
		<h1>Enjoy Your Luxury Taxi With Low Prices<span class="dot">.</span></h1>
		<p>
			Relax in comfort and arrive in style while saving money with our reliable carpooling service. Book your ride today and experience the difference!
		</p>
		<img src="{% static 'images/taxi-2.png'%}"/>
	</section>
	<section class="steps">
		<h4>How We Work</h4>
		<h1>Easy Steps For Booking A Ride<span class="dot">.</span></h1>
		<p>
			Simply enter your pickup and dropoff locations, select a ride, and confirm your booking. It's that easy!
		</p>
		<ul class="steps-list">
			<li>
				<div>
					<i class="fas fa-light fa-location"></i>
				</div>
				<h3>Select Destination</h3>
				<p>
					Choose your desired destination for the ride.
				</p>
			</li>
			<li>
				<div>
					<i class="fas fa-light fa-car"></i>
				</div>
				<h3>Get A Match</h3>
				<p>
					Once you request a ride, we'll match you with a suitable driver.
				</p>
			</li>
			<li>
				<div>
					<i class="fas fa-light fa-wallet"></i>
				</div>
				<h3>Pay For Ride</h3>
				<p>
					Easily pay for your ride through our secure payment system.
				</p>
			</li>
			<li>
				<div>
					<i class="fas fa-light fa-award"></i>
				</div>
				<h3>Enjoy Your Ride</h3>
				<p>
					Sit back, relax, and enjoy your comfortable ride.
				</p>
			</li>
		</ul>
	</section>
	<section class="experience" style="flex-direction: column;">
		<h4>Our Experience</h4>
		<h1>We have been providing great carpooling service since 2004<span class="dot">.</span></h1>
		<p style="margin-top: 0">
			Relax in comfort and arrive in style while saving money with our reliable carpooling service. Book your ride today and experience the difference!
		</p>
		<div class="experience-metric">
			<div>
				<h1>
					<span class="counter" data-number="167">0</span>
					<i class="fas fa-plus"></i>
				</h1>
				<p>Our Taxi Units</p>
			</div>
			<div>
				<h1>
					<span class="counter" data-number="2820">0</span>
					<i class="fas fa-plus"></i>
				</h1>
				<p>Happy Customers</p>
			</div>
			<div>
				<h1>
					<span class="counter" data-number="25">0</span>
					<i class="fas fa-plus"></i>
				</h1>
				<p>Years Of Experience</p>
			</div>
			<div>
				<h1>
					<span class="counter" data-number="1825">0</span>
					<i class="fas fa-plus"></i>
				</h1>
				<p>App Downloads</p>
			</div>
		</div>
	</section>
	<section class="team">
		<div>
			<h4>Our Team</h4>
			<h1>Meet Our Expert Team<span class="dot">.</span></h1>
			<p>Our team is made up of experienced professionals who are passionate about providing safe, reliable, and affordable carpooling solutions.</p>
			<a href="/team">Show All Team</a>
		</div>
		<div class="team-ceo team-card">
			<div>
				<p>Hope Iyamu</p>
				<h5>CoRider Founder</h5>
			</div>
		</div>
		<div class="team-manager team-card">
			<div>
				<p>Jesse Livermore</p>
				<h5>CoRider Manager</h5>
			</div>
		</div>
	</section>
{% endblock %}

rides/templates/rides/edit-account.html
{% extends 'rides/main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
	<link rel="stylesheet" href="{% static 'css/account-main.css' %}">
	<link rel="stylesheet" href="{% static 'css/edit-account.css' %}">
	<script src="{% static 'js/edit-account.js' %}" defer></script>
{% endblock %}
{% block content %}
	<section class="edit-account">
		<div>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<p class="profile-image">
				{% if request.user.profile_picture %}
        			<img src="{{ request.user.profile_picture.url }}" alt="profile picture" width='100' height='100' class="profile-picture"/>
        		{% else %}
        			<img src="{% static 'images/profile-picture.png' %}" alt="profile picture" width='100' height='100' class="profile-picture"/>
        		{% endif %}
        		{% if account_form.errors %}
					<span class="change-avatar" style="color: red;">profile picture is required</span>
				{% endif %}
        		<span class="change-avatar" onClick="document.querySelector('#id_profile_picture').click()">Change Avatar</span>
        		<input type="file" name="profile_picture" accept="image/*" class="hidden" id="id_profile_picture">
    		</p>
    		<div class="alert alert-danger account-errors" role="alert"></div>
			<p class="form-group">
        		<label for="{{ account_form.first_name.id_for_label }}">First Name<span class="req">*</span></label>
        		{{ account_form.first_name|attr:"class:form-control"|attr:"required:true" }}
    		</p>
    		<p class="form-group">
        		<label for="{{ account_form.last_name.id_for_label }}">Last Name<span class="req">*</span></label>
        		{{ account_form.last_name|attr:"class:form-control"|attr:"required:true" }}
    		</p>
    		<div class="form-col">
    		<p class="form-group">
        		<label for="{{ account_form.gender.id_for_label }}">Gender<span class="req">*</span></label>
        		{{ account_form.gender|attr:"class:form-control"|attr:"required:true" }}
    		</p>
    		<p class="form-group">
        		<label for="{{ account_form.birthday.id_for_label }}">Birthday</label>
        		{{ account_form.birthday|attr:"class:form-control" }}
    		</p>
    		</div>
    		<p class="form-group">
        		<label for="{{ account_form.email.id_for_label }}">Email</label>
        		{{ account_form.email|attr:"class:form-control" }}
    		</p>
    		<p class="form-group">
        		<label for="{{ account_form.phone_number.id_for_label }}">Phone Number<span class="req">*</span></label>
        		{{ account_form.phone_number|attr:"class:form-control"|attr:"required:true" }}
    		</p>
    		<p class="form-group">
        		<label for="{{ account_form.address.id_for_label }}">Address<span class="req">*</span></label>
        		{{ account_form.address|attr:"class:form-control"|attr:"required:true" }}
    		</p>
    		<div class="form-col">
    		<p class="form-group">
        		<label for="{{ account_form.zip_code.id_for_label }}">Zip Code</label>
        		{{ account_form.zip_code|attr:"class:form-control"}}
    		</p>
    		<p class="form-group">
        		<label for="{{ account_form.driver_id.id_for_label }}">Driver's License ID</label>
        		{{ account_form.driver_id|attr:"class:form-control" }}
    		</p>
    		</div>
    		
		
		<h3 id="vehicle">Vehicle Information</h3>
		<div class="alert alert-danger vehicle-errors" role="alert"></div>
		
			{% csrf_token %}
			{% if vehicle_form.errors %}
				<div class="alert alert-danger" role="alert">
					{{ vehicle_form.errors }}
				</div>
			{% endif %}
			<div class="form-col">
				<p class="form-group">
					<label for="{{ vehicle_form.make.id_for_label }}">Make</label>
					{{ vehicle_form.make|attr:"class:form-control"}}
				</p>
				<p class="form-group">
					<label for="{{ vehicle_form.model.id_for_label }}">Model</label>
					{{ vehicle_form.model|attr:"class:form-control"}}
				</p>
			</div>
			<div class="form-col">
				<p class="form-group">
					<label for="{{ vehicle_form.color.id_for_label }}">Color</label>
					{{ vehicle_form.color|attr:"class:form-control" }}
				</p>
				<p class="form-group">
					<label for="{{ vehicle_form.plate_number.id_for_label }}">Plate Number</label>
					{{ vehicle_form.plate_number|attr:"class:form-control" }}
				</p>
			</div>
			<button type="submit" class="save-btn">Update</button>
		</form>
		
		</div>
	</section>
{% endblock %}